GET http://localhost:3000/api/v1/epics
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTY0MDM1NTM1MSwiZXhwIjoxNjQwNDQxNzUxfQ.kkDQ0ecdQ1oXuAXOModR5_CNgbmna-X9jo6GGIPV5Q0

###

POST http://localhost:3000/api/v1/epics
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTY0MDM1NTM1MSwiZXhwIjoxNjQwNDQxNzUxfQ.kkDQ0ecdQ1oXuAXOModR5_CNgbmna-X9jo6GGIPV5Q0

{
  "name": "Epic 3"
} 

###

PUT http://localhost:3000/api/v1/epics/1
Content-Type: application/json

{
  "name": "Epic changed"
}

###

DELETE http://localhost:3000/api/v1/epics/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTY0MDM1NTM1MSwiZXhwIjoxNjQwNDQxNzUxfQ.kkDQ0ecdQ1oXuAXOModR5_CNgbmna-X9jo6GGIPV5Q0

###

GET http://localhost:3000/api/v1/categories
Authorization: 2

###

GET http://localhost:3000/api/v1/categories/1

###

POST http://localhost:3000/api/v1/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTY0MDM1NTM1MSwiZXhwIjoxNjQwNDQxNzUxfQ.kkDQ0ecdQ1oXuAXOModR5_CNgbmna-X9jo6GGIPV5Q0 

{
  "name": "Category 1",
  "epic_id": 1
}

###

PUT http://localhost:3000/api/v1/categories/1
Content-Type: application/json

{
  "name": "Category changed"
}

###

DELETE http://localhost:3000/api/v1/categories/4

###

POST http://localhost:3000/api/v1/items
Content-Type: application/json

{
  "name": "Item 1",
  "category_id": 5
}

###

GET http://localhost:3000/api/v1/items

###

GET http://localhost:3000/api/v1/items?epic_id=2

###

GET http://localhost:3000/api/v1/items/1

###

PUT http://localhost:3000/api/v1/items/1
Content-Type: application/json

{
  "category_id": 4
}

###

DELETE http://localhost:3000/api/v1/items/2

###

POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
  "username": "ashwin2",
  "password": "password"
}

###

POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "username": "ashwin2",
  "password": "password"
}

###

POST http://localhost:3000/api/v1/auth/token
Content-Type: application/json

{
  "username": "ashwin",
  "password": "password"
}

###