GET http://localhost:3000/api/v1/epics

###

POST http://localhost:3000/api/v1/epics
Content-Type: application/json

{
  "name": "Epic 1"
}

###

PUT http://localhost:3000/api/v1/epics/1
Content-Type: application/json

{
  "name": "Epic changed"
}

###

DELETE http://localhost:3000/api/v1/epics/4

###

GET http://localhost:3000/api/v1/categories

###

GET http://localhost:3000/api/v1/categories/1

###

POST http://localhost:3000/api/v1/categories
Content-Type: application/json

{
  "name": "Category 2",
  "epic_id": 1
}

###

PUT http://localhost:3000/api/v1/categories/1
Content-Type: application/json

{
  "name": "Category changed"
}

###

DELETE http://localhost:3000/api/v1/categories/4

###

POST http://localhost:3000/api/v1/items
Content-Type: application/json

{
  "name": "Item 1",
  "category_id": 5
}

###

GET http://localhost:3000/api/v1/items

###

GET http://localhost:3000/api/v1/items?epic_id=2

###

GET http://localhost:3000/api/v1/items/1

###

PUT http://localhost:3000/api/v1/items/1
Content-Type: application/json

{
  "category_id": 4
}

###

DELETE http://localhost:3000/api/v1/items/2

###